Use new ClientSession for each http request
I do not know why, but after a batch size (default 1000) completes,
I very frequently get the exception pasted at the bottom of this message.

From my research, it looks like this indicates that the client session
closed, and the server tried to write it a message but couldn't.

I do not know why the client session would close for me. Maybe it is
a timeout or something? If we can figure out why and fix it, we should
go back to the previous way of using one ClientSession for the whole
script, because that is what is recommended by the official documentation.

Anyways, for now, a new client session for each request seems to fix it
for me, as was also what fixed someone's similar problem here:

https://stackoverflow.com/a/54711974

2020-12-15 11:41:42,987 - ingest - INFO - Loading ./Datasets/metatlas.json.
2020-12-15 11:42:02,258 - ingest - INFO - File contains 107486 molecules.
2020-12-15 11:42:02,258 - ingest - INFO - Ingesting in batches of 1000
  1%|▌                                                            | 999/107486 [01:37<9:46:45,  3.02 structures/s]Traceback (most recent call last):
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 585, in write_bytes
    await self.body.write(writer)
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/aiohttp/payload.py", line 239, in write
    await writer.write(self._value)
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/aiohttp/http_writer.py", line 107, in write
    self._write(chunk)
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "ingest.py", line 141, in <module>
    main()
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "ingest.py", line 136, in main
    asyncio.run(
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "ingest.py", line 109, in ingest
    await f
  File "/usr/lib/python3.8/asyncio/tasks.py", line 608, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "ingest.py", line 75, in ingest_molecule
    r = await gc.post('molecules',  raise_for_status=False, json=data)
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/tenacity/_asyncio.py", line 79, in async_wrapped
    return await fn(*args, **kwargs)
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/tenacity/_asyncio.py", line 42, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/tenacity/__init__.py", line 360, in iter
    return fut.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/tenacity/_asyncio.py", line 45, in __call__
    result = await fn(*args, **kwargs)
  File "ingest.py", line 44, in post
    async with self._session.post('%s/%s' % (self._api_url, path),
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno None] Can not write request body for http://localhost:8080/api/v1/molecules
  1%|▌                                                           | 1000/107486 [01:37<2:53:13, 10.25 structures/s]

Signed-off-by: Patrick Avery <patrick.avery@kitware.com>